# Generated by Django 4.0.5 on 2022-07-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author_post_tags_alter_author_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_name',
            field=models.ImageField(upload_to='posts'),
        ),
    ]
